### FETCH ALL TASKS
GET HTTP://localhost:3200/tasks
Content-Type: application/json

### CREATE A TASK
POST HTTP://localhost:3200/tasks
Content-Type: application/json

{
    "title": "title_3",
    "date": "2024/04/11",
    "description": "desc_3",
    "priority": "normal",
    "status": "inProgress"
}

### UPDATE A TASK
PUT HTTP://localhost:3200/tasks
Content-Type: application/json

{
    "id": "3ff118fe-5b73-4354-8a6a-982b67a0cb0c",
    "status": "completed"
}

### DELETE A TASK
DELETE HTTP://localhost:3200/tasks
Content-Type: application/json

{
    "id": "8b7ac3a3-8692-40d4-a10d-8d4e8ff32714"
}